import type { Metadata } from "next";
import Image from "next/image";
import { Inter } from "next/font/google";
import "./globals.css";
import Logo from "@/assets/react-quiz-logo.svg";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#2b2737] p-4 max-w-full m-auto flex flex-col items-center`}>
        <Image className="h-[80px] sm:h-full" src={Logo} alt="logo" />
        {children}
      </body>
    </html>
  );
}
